import React, { useState, useEffect, useCallback } from 'react';
import { Camera, SecurityAlert, DashboardStats, SystemSettings, UserProfile } from './types';
import { api } from './services/api';
import { SplashScreen } from './components/SplashScreen';
import { LoginScreen } from './components/LoginScreen';
import { Navbar } from './components/Navbar';
import { Sidebar } from './components/Sidebar';
import { DashboardView } from './components/DashboardView';
import { LiveScannerView } from './components/LiveScannerView';
import { AxisCameraView } from './components/AxisCameraView';
import { AlertCenterView } from './components/AlertCenterView';
import { DetectionHistoryView } from './components/DetectionHistoryView';
import { SecurityReportsView } from './components/SecurityReportsView';
import { SettingsView } from './components/SettingsView';
import { AlertDetailModal } from './components/AlertDetailModal';
import { DemoTourModal } from './components/DemoTourModal';

export default function App() {
  // App Lifecycle States
  const [showSplash, setShowSplash] = useState<boolean>(true);
  const [isAuthenticated, setIsAuthenticated] = useState<boolean>(false);
  const [currentTab, setCurrentTab] = useState<string>('dashboard');

  // User Profile
  const [user, setUser] = useState<UserProfile>({
    name: 'Officer Rajesh Sharma',
    email: 'r.sharma@krishnalabs.com',
    role: 'Chief Security Officer (Tier 1)',
    badgeNumber: 'KLS-SOC-804',
    stationId: 'SOC-TERMINAL-01',
  });

  // App Domain Data
  const [cameras, setCameras] = useState<Camera[]>([]);
  const [alerts, setAlerts] = useState<SecurityAlert[]>([]);
  const [stats, setStats] = useState<DashboardStats | null>(null);
  const [settings, setSettings] = useState<SystemSettings>({
    confidenceThreshold: 75,
    alertCooldownSeconds: 5,
    soundAlertEnabled: true,
    autoEmailAlerts: true,
    logRetentionDays: 30,
    supportedWeaponTypes: ['gun', 'knife', 'rifle', 'blade'],
    cameraScanFps: 30,
    enableWebcamFallback: true,
  });

  // Sound and UI Modals State
  const [soundEnabled, setSoundEnabled] = useState<boolean>(true);
  const [selectedAlertForModal, setSelectedAlertForModal] = useState<SecurityAlert | null>(null);
  const [isDemoTourOpen, setIsDemoTourOpen] = useState<boolean>(false);
  const [scannerTargetCameraId, setScannerTargetCameraId] = useState<string | undefined>(undefined);

  // Load all initial data from backend API
  const refreshAllData = useCallback(async () => {
    try {
      const [cams, alts, st, sett] = await Promise.all([
        api.getCameras(),
        api.getAlerts(),
        api.getDashboardStats(),
        api.getSettings(),
      ]);
      setCameras(cams);
      setAlerts(alts);
      setStats(st);
      if (sett) setSettings(sett);
    } catch (err) {
      console.error('Failed to load initial data:', err);
    }
  }, []);

  // Effect to load data after authentication
  useEffect(() => {
    if (isAuthenticated) {
      refreshAllData();
      // Polling interval for live status updates
      const interval = setInterval(() => {
        refreshAllData();
      }, 10000);
      return () => clearInterval(interval);
    }
  }, [isAuthenticated, refreshAllData]);

  // Handle Login
  const handleLogin = (officer: UserProfile) => {
    setUser(officer);
    setIsAuthenticated(true);
  };

  // Handle Logout
  const handleLogout = () => {
    setIsAuthenticated(false);
  };

  // Triggered when a new alert is generated by Live Scanner
  const handleNewAlertTriggered = (newAlert: SecurityAlert) => {
    setAlerts((prev) => [newAlert, ...prev.filter((a) => a.id !== newAlert.id)]);
    if (stats) {
      setStats({
        ...stats,
        activeAlerts: stats.activeAlerts + 1,
        todayDetections: stats.todayDetections + 1,
      });
    }
  };

  // Switch to Scanner from Camera fleet view
  const handleSelectCameraToScan = (camId: string) => {
    setScannerTargetCameraId(camId);
    setCurrentTab('scanner');
  };

  // Handle splash screen exit
  if (showSplash) {
    return <SplashScreen onComplete={() => setShowSplash(false)} />;
  }

  // Handle login screen
  if (!isAuthenticated) {
    return <LoginScreen onLoginSuccess={handleLogin} />;
  }

  const activeAlertsCount = alerts.filter((a) => a.status === 'ACTIVE').length;
  const onlineCamerasCount = cameras.filter((c) => c.status === 'ONLINE').length;

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 flex flex-col font-sans selection:bg-sky-500 selection:text-white antialiased">
      {/* Top Fixed Navigation Bar */}
      <Navbar
        user={user}
        activeAlerts={alerts}
        soundEnabled={soundEnabled}
        onToggleSound={() => setSoundEnabled(!soundEnabled)}
        onLogout={handleLogout}
        onOpenDemoTour={() => setIsDemoTourOpen(true)}
        onSelectAlert={(alt) => setSelectedAlertForModal(alt)}
        onNavigate={(tab) => setCurrentTab(tab)}
        currentTab={currentTab}
      />

      {/* Main Layout Container */}
      <div className="flex-1 flex overflow-hidden">
        {/* Left Navigation Sidebar */}
        <Sidebar
          currentTab={currentTab}
          onSelectTab={(tab) => setCurrentTab(tab)}
          activeAlertsCount={activeAlertsCount}
          onlineCamerasCount={onlineCamerasCount}
          onOpenDemoTour={() => setIsDemoTourOpen(true)}
        />

        {/* Center Main Dynamic View Area */}
        <main className="flex-1 overflow-y-auto bg-slate-950/40 min-h-[calc(100vh-61px)]">
          {currentTab === 'dashboard' && (
            <DashboardView
              stats={stats}
              cameras={cameras}
              alerts={alerts}
              onNavigate={(tab) => setCurrentTab(tab)}
              onSelectAlert={(alt) => setSelectedAlertForModal(alt)}
              onRefresh={refreshAllData}
              onOpenDemoTour={() => setIsDemoTourOpen(true)}
            />
          )}

          {currentTab === 'scanner' && (
            <LiveScannerView
              cameras={cameras}
              selectedCameraId={scannerTargetCameraId}
              onTriggerAlert={handleNewAlertTriggered}
              soundEnabled={soundEnabled}
              onToggleSound={() => setSoundEnabled(!soundEnabled)}
            />
          )}

          {currentTab === 'cameras' && (
            <AxisCameraView
              cameras={cameras}
              onRefresh={refreshAllData}
              onSelectCameraToScan={handleSelectCameraToScan}
            />
          )}

          {currentTab === 'alerts' && (
            <AlertCenterView
              alerts={alerts}
              onRefresh={refreshAllData}
              onSelectAlert={(alt) => setSelectedAlertForModal(alt)}
              officerName={user.name}
            />
          )}

          {currentTab === 'history' && (
            <DetectionHistoryView
              alerts={alerts}
              cameras={cameras}
              onSelectAlert={(alt) => setSelectedAlertForModal(alt)}
            />
          )}

          {currentTab === 'reports' && (
            <SecurityReportsView
              alerts={alerts}
              cameras={cameras}
              stats={stats}
              officerName={user.name}
            />
          )}

          {currentTab === 'settings' && (
            <SettingsView
              settings={settings}
              user={user}
              onUpdateSettings={(newSett) => setSettings(newSett)}
              onUpdateUser={(newU) => setUser(newU)}
            />
          )}
        </main>
      </div>

      {/* Alert Details Modal */}
      {selectedAlertForModal && (
        <AlertDetailModal
          alert={selectedAlertForModal}
          onClose={() => setSelectedAlertForModal(null)}
          onAcknowledge={async (altId) => {
            await api.acknowledgeAlert(altId, user.name);
            refreshAllData();
          }}
          officerName={user.name}
        />
      )}

      {/* Interactive 1-Click Presentation Tour Modal */}
      <DemoTourModal
        isOpen={isDemoTourOpen}
        onClose={() => setIsDemoTourOpen(false)}
        onNavigate={(tab) => setCurrentTab(tab)}
      />
    </div>
  );
}
